# Generated by Django 3.1.2 on 2020-11-10 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('murdochpolicyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-category_name']},
        ),
        migrations.AlterModelOptions(
            name='documenttype',
            options={'ordering': ['-document_type']},
        ),
    ]
