# Generated by Django 3.1.2 on 2020-11-11 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('murdochpolicyapp', '0002_auto_20201110_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
