# Generated by Django 3.1.2 on 2020-11-11 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('murdochpolicyapp', '0003_auto_20201111_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_size',
            field=models.IntegerField(default=1),
        ),
    ]
