# Generated by Django 3.1.2 on 2020-11-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('murdochpolicyapp', '0004_auto_20201111_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
